---
name: 解析 GTNewHorizons/GT-New-Horizons-Modpack 中 任务书 lang 文件 到 ParaTranz

description: 将特定 commit SHA 的任务书 lang 文件解析到 ParaTranz (仅内部使用)

labels: [ '自动化:questbook→paratranz' ]

body:
  - type: input
    id: commit-sha
    attributes:
      label: 任务书 lang 文件 commit SHA
      value: 'master'
    validations:
      required: false
