---
name: 使用 ParaTranz 数据 生成 汉化任务书 lang 文件
description: 使用 ParaTranz 数据 生成 汉化任务书 lang 文件 并 创建提交到 特定分支 的 PR (仅内部使用)

labels: [ '自动化:paratranz→questbook' ]

body:
  - type: input
    id: branch
    attributes:
      label: PR 提交分支
    validations:
      required: true
  - type: input
    id: commit-sha
    attributes:
      label: 任务书 json 文件 commit SHA
      value: 'master'
    validations:
      required: false
