name: 3. Gt Lang To Paratranz

on:
  workflow_dispatch:
    inputs:
      gt-lang-url:
        description: "GregTech.lang url"
        required: true
        type: string

env:
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
  PARATRANZ_PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}

jobs:
  gt-lang-to-paratranz:
    name: Gt Lang To Paratranz
    runs-on: ubuntu-latest
    steps:
      - name: Setup Compare Repo
        uses: Kiwi233/Translation-of-GTNH/.github/actions/setup-compare-repo@master

      - name: Setup Bun
        uses: Kiwi233/Translation-of-GTNH/.github/actions/setup-bun@master

      - name: Run Script
        run: >-
          bun run src/index.ts to-paratranz:gt-lang
          --gt-lang-url='${{ github.event.inputs.gt-lang-url }}'

      - name: Print success summary
        run: |
          echo "## 已自动同步GregTech.lang至Paratranz" >> $GITHUB_STEP_SUMMARY
          echo "GregTech.lang URL: ${{ github.event.inputs.gt-lang-url }}" >> $GITHUB_STEP_SUMMARY
