name: 3. Lang And Zs To Paratranz

on:
  workflow_dispatch:

env:
  PARATRANZ_TOKEN: ${{ secrets.PARATRANZ_TOKEN }}
  PARATRANZ_PROJECT_ID: ${{ secrets.PARATRANZ_PROJECT_ID }}

  REPO_PATH: .repo.local.d
  DAILY_HISTORY_PATH: .gtnh-translations.local.d/daily-history

jobs:
  lang-and-zs-to-paratranz:
    name: Lang And Zs To Paratranz
    runs-on: ubuntu-latest
    steps:
      - name: Setup Compare Repo
        uses: Kiwi233/Translation-of-GTNH/.github/actions/setup-compare-repo@master

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPO_PATH }}

      - name: Checkout GTNH-Translations (daily-history only)
        uses: actions/checkout@v4
        with:
          repository: GTNewHorizons/GTNH-Translations
          ref: master
          path: .gtnh-translations.local.d
          sparse-checkout: |
            daily-history
          sparse-checkout-cone-mode: true

      - name: Setup Bun
        uses: Kiwi233/Translation-of-GTNH/.github/actions/setup-bun@master

      - name: Patch Compare Scripts
        run: |
          cp ${{ env.REPO_PATH }}/.github/gtnh-compare-patches/rules.ts src/paratranz/converter/rules.ts
          cp ${{ env.REPO_PATH }}/.github/gtnh-compare-patches/converter-index.ts src/paratranz/converter/index.ts

      - name: Lang And Zs To Paratranz (from daily-history)
        run: >-
          bun run src/index.ts to-paratranz:lang-zs
          --modpack-path='${{ env.DAILY_HISTORY_PATH }}'
          --extra-lang='resources/**/en_US.lang'
          --extra-lang='config/**/en_US.lang'
